# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (26 is current forge version)
license="MIT"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="jumpquilt" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="JumpQuilt" #mandatory
# A text field displayed in the mod UI
authors="comp500, kb1000" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Allows the use of Quilt mods in Twitch modpacks, by loading Quilt as if it were a Forge mod.
'''
